### ISSUE TITLE
Allow several URIs for shovel

### ISSUE THREAD

**Issue by pierrre** [michaelklishin/rabbit-hole#103]
https://www.rabbitmq.com/shovel-dynamic.html
About `src-uri` and `dest-uri`:
> Note that this field can either be a string, or a list of strings. If more than one string is provided, the shovel will randomly pick one URI from the list. This can be used to connect to a cluster and ensure the link will eventually find another node in the event that one fails.

In my own Shovel wrapper, I use `interface{}` type for these fields.
So I can provide both `string` and `[]string`.
It works fine.
Maybe for safety we could add a check at runtime for the type.

May I submit a PR ?

**Comment by pathcl** [comment]
I faced a problem today regarding shovels and this issue its related:
```
json: cannot unmarshal array into Go struct field ShovelDefinition.value.src-uri of type string
```
