### ISSUE TITLE
List queues error

### ISSUE THREAD

**Issue by igsky** [michaelklishin/rabbit-hole#107]
Calling `rmqc.ListQueues()` causes  `json: cannot unmarshal string into Go struct field QueueInfo.consumer_utilisation of type float64`

If I change `ConsumerUtilisation` type to `string` then it causes `json: cannot unmarshal string into Go struct field QueueInfo.consumer_utilisation of type string`

Looks like `ConsumerUtilisation` of type `string` works fine as long as there are no actual consumers. So API is inconsistent in this regard.

**Comment by michaelklishin** [comment]
@igsky this is https://github.com/rabbitmq/rabbitmq-management/issues/26. I cannot suggest anything beyond since you haven't provided a way to reproduce or even any details on the RabbitMQ version used.

**Comment by igsky** [comment]
Cropped rabbitmqctl output:

> {running_applications,
>      [{rabbitmq_management,"RabbitMQ Management Console","3.3.5"},
>       {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.3.5"},
>       {webmachine,"webmachine","1.10.3-rmq3.3.5-gite9359c7"},
>       {mochiweb,"MochiMedia Web Server","2.7.0-rmq3.3.5-git680dba8"},
>       {rabbitmq_management_agent,"RabbitMQ Management Agent","3.3.5"},
>       {rabbit,"RabbitMQ","3.3.5"},
>       {os_mon,"CPO  CXC 138 46","2.3"},
>       {inets,"INETS  CXC 138 49","5.10.3"},
>       {mnesia,"MNESIA  CXC 138 12","4.12.3"},
>       {amqp_client,"RabbitMQ AMQP Client","3.3.5"},
>       {xmerl,"XML parser","1.3.7"},
>       {sasl,"SASL  CXC 138 11","2.4.1"},
>       {stdlib,"ERTS  CXC 138 10","2.2"},
>       {kernel,"ERTS  CXC 138 10","3.0.3"}]},
>  {os,{unix,linux}},
>  {erlang_version,
>      "Erlang/OTP 17 [erts-6.2] [source] [64-bit] [smp:4:4] [async-threads:30] [kernel-poll:true]\n"}

Well it looks like rabbitmq version incompatibility then. Thanks for the help!
