### ISSUE TITLE
Support GET|PUT|DELETE /api/topic-permissions/{vhost}/{user}

### ISSUE THREAD

**Issue by carstenlenz** [michaelklishin/rabbit-hole#111]
Hi :)

We would like to use the topic permissions feature in RabbitMQ.
This is a feature that requires RabbitMQ >= 3.7.0 

How do you think about this? Is this at all considerable?

If yes, then we could maybe provide a PR

Cheers
Carsten

**Comment by michaelklishin** [comment]
We obviously want to support all API endpoints (as long as we can do it in a way that makes sense). A PR would be appreciated. Please take a look at the test suite, how a RabbitMQ node they run against needs to be pre-configured (e.g. from `.travis.yml`) and include tests.

**Comment by michaelklishin** [comment]
[CONTRIBUTING.md](https://github.com/michaelklishin/rabbit-hole/blob/master/CONTRIBUTING.md) is still mostly accurate but Travis config is where all the gory details are.

**Comment by michaelklishin** [comment]
Contributed by @BarnabyShearer in #125.
