### ISSUE TITLE
Need additional attributes in NodeInfo of node.go file and QueueInfo of queue.go

### ISSUE THREAD

**Issue by Durgababu** [michaelklishin/rabbit-hole#115]
Hi, 
I need few more attributes in NodeInfo and QueueInfo structures, which are available in same json responses.

In NodeInfo structure of node.go file , I need below two attributes additionally ...

ProcUsed      int  `json:"proc_used"`
ProcTotal     int  `json:"proc_total"`

In QueueInfo structures of queue.go file, need below attribute additionally....

ActiveConsumers     int64   `json:"active_consumers"`

Only these lines should be included in the code. No further changes required as we have these attributes available in response jsons.

Please do the changes and commit, so that i can use the latest package.

**Comment by jordanbcooper** [comment]
I actually opened a PR for proc_used and proc_total, haven't heard back yet.

**Comment by jordanbcooper** [comment]
@durgababu -- attributes in my above comment were merged.

**Comment by opsramp** [comment]
@jordanbcooper -- Yeah, i checked. Your changes are merged. But sill i need one more change to be merged. Let me create new merge request. 

Below are my changes...
In QueueInfo structures of queue.go file, need below attribute additionally....

ActiveConsumers int64 json:"active_consumers"

**Comment by Durgababu** [comment]
@jordanbcooper -- Yeah, i checked. Your changes are merged. But sill i need one more change to be merged. Let me create new merge request.

Below are my changes...
In QueueInfo structures of queue.go file, need below attribute additionally....

ActiveConsumers int64 json:"active_consumers"

**Comment by michaelklishin** [comment]
Addressed in #113 and #117.
