### ISSUE TITLE
Release 1.5.0

### ISSUE THREAD

**Issue by pierrre** [michaelklishin/rabbit-hole#120]
Hello !

Could you release a new tagged version ?
`v1.4.0` is 1 year old, and there are several interesting changes since then.

**Comment by michaelklishin** [comment]
@pierrre `v1.5.0-rc.1` is tagged. Please give it a try.

**Comment by pierrre** [comment]
Thank you, it works !

**Comment by michaelklishin** [comment]
`v1.5.0` has been tagged.
