### ISSUE TITLE
Invalid URI encoding with `req.URL.Opaque`

### ISSUE THREAD

**Issue by leominov** [michaelklishin/rabbit-hole#121]
Current code base:

```
// set Opaque to preserve the percent-encoded path.
req.URL.Opaque = "//" + client.host + "/api/" + path
```

giving strange result:

```
GET http://skipped.host.name/api/whoami HTTP/1.1
Host: skipped.host.name
Connection: close
```

and response on it:

```
HTTP/1.1 404 Not Found
Date: Wed, 26 Dec 2018 14:37:00 GMT
Server: envoy
Content-Length: 0
```

But must be:

```
GET /api/whoami HTTP/1.1
Host: skipped.host.name
```

Go version:

```
$ go version
go version go1.11 darwin/amd64
```

**Comment by leominov** [comment]
If I replace on: `req.URL.Opaque = "/api/" + path` – works fine.

**Comment by michaelklishin** [comment]
That line is from 2013 or so when Go's URL handling had idiosyncrasies around percent-encoding in path IIRC. That said, this is the first time this is reported in over 5 years so there must be something specific to your environment.

A quick test suggests that messing with `URL.Opaque` is no longer necessary, the path is %-encoded correctly (there is a virtual host with a slash in the test suite).

**Comment by leominov** [comment]
👍
