### ISSUE TITLE
Support RabbitMQ path_prefix

### ISSUE THREAD

**Issue by arnoutvw** [michaelklishin/rabbit-hole#122]
In my rabbitmq.conf, I have de following definition:
`{rabbitmq_management, [
    {path_prefix, "app/rabbitmq"}
  ]}`
So RabbitMQ is available on a http://<host>:<port>/app/rabbitmq

When I configure the endpoint url to that address it ignores the path /app/rabbitmq and calls the api on the root. I have seen this with Wireshark. 
Probably an issue with: req.URL.Opaque ?

**Comment by michaelklishin** [comment]
I don't see why specifying the correct path in the endpoint would not work. There isn't much that can be suggested without an example snippet of code and captured request and response.
