### ISSUE TITLE
Support creating an internal exchange

### ISSUE THREAD

**Issue by jgulotta** [michaelklishin/rabbit-hole#130]
The current `ExchangeSettings` does not include an `Internal` parameter, which prevents declaring an internal exchange. From [the documentation](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.14/priv/www/api/index.html)

> To PUT an exchange, you will need a body looking something like this:
> ```json
> {"type":"direct","auto_delete":false,"durable":true,"internal":false,"arguments":{}}
> ```

I think this is the only change necessary, but I am not currently in a position to validate it so I'm opening an issue instead of a PR.

```diff
diff --git a/exchanges.go b/exchanges.go
index 1191ade..7f6852c 100644
--- a/exchanges.go
+++ b/exchanges.go
@@ -33,6 +33,7 @@ type ExchangeSettings struct {
        Type       string                 `json:"type"`
        Durable    bool                   `json:"durable"`
        AutoDelete bool                   `json:"auto_delete,omitempty"`
+       Internal   bool                   `json:"internal,omitempty"`
        Arguments  map[string]interface{} `json:"arguments,omitempty"`
 }
```

**Comment by michaelklishin** [comment]
Internal exchanges are not meant to be used by applications. They were introduced for the needs of the Federation plugin.

**Comment by jgulotta** [comment]
That's why I need them, and for dead letter exchanges. I don't want to create or use internal exchanges from applications. This client is used by Terraform which we use to provision our infrastructure. Without this change and an update from Terraform we have to use some hacky workaround scripts instead of being able to rely on the Terraform provider. Please reconsider adding the feature, mirroing the API that RabbitMQ itself supports.

**Comment by michaelklishin** [comment]
Those who have an infrastructure that uses internal exchanges by definition use one of the plugins that relies on this internal feature. If you absolutely must re-create the exact topology elsewhere but without using those plugins (I fail to see why this would be necessary), it is perfectly possible to [export and import it using a definition file](https://www.rabbitmq.com/definitions.html).

I remain unconvinced that there is any need in allowing applications, Terraform providers or anything other than RabbitMQ plugins and definition import, to be able to set this flag.

**Comment by michaelklishin** [comment]
After discussing with with several other members of the RabbitMQ core team we have a consensus that exposing this property is not necessary and internal features should stay internal.

Internal exchanges are only declared by RabbitMQ plugins, namely federation. When provisioning a cluster, Terraform or any other user has several options:

 * Set up federation upstream and policies and let federation declare the exchanges it needs, when it's time to do so
 * Export definitions and import them

Declaring every single topology item using Terraform (or similar) resources is not necessary and likely means the operator does not fully understand how certain RabbitMQ features work, namely that federation sets up its own resources and may
use internal properties or markers that applications are not expected to use or care about.

**Comment by jgulotta** [comment]
> Those who have an infrastructure that uses internal exchanges by definition use one of the plugins that relies on this internal feature. . .Internal exchanges are only declared by RabbitMQ plugins, namely federation

This is inaccurate. We have internal exchanges that have nothing to do with the federation plugin. Moreover, it is completely possible to declare and use internal exchanges from the official Java RabbitMQ client without any plugins whatsoever, and the flag is in documented AMQP 0.9.1 reference and the documented HTTP API . If it were purely a RabbitMQ server/plugin implementation detail this flag should not be part of the stable public API.

> I remain unconvinced that there is any need in allowing applications, Terraform providers or anything other than RabbitMQ plugins and definition import, to be able to set this flag.

I think there are several justifying points

- Such infrastructure already exists in the wild and the lack of an `internal` flag makes this client (and anything depending on it) impossible to use for recreating that infrastructure
- Lower-level clients like this should faithfully implement the protocols exposed by the server, which in this instance includes the `internal` flag. The flag may be deprecated in 0.9.1 and the HTTP API, but it is not removed, and therefore should be available in any client implementing that version of the protocol/API
- The fact that it's exposed in official clients and in documentation means this flag is already not an internal (i.e. server/plugin only) feature so the argument that it should "stay internal" is obviated.
- It's perfectly reasonable to want exchange-to-exchange routing outside of a plugin while also wishing to restrict direct publishes, which is exactly the use case for the `internal` flag, and the flag is way more convenient than trying to derive a regex for authorization that accounts for every currently known exchange without interfering with their ability to bind to arbitrary queues and which requires updates for any future such exchange for every current and future user
- While there may be workarounds via other scripts or definition import/export, those are _workarounds_ for functionality missing in the client. They are inconvenient and inconsistent and, in our case, would move the source of truth for what defines our topology

> When provisioning a cluster, Terraform or any other user has several options. . .

This may be reasonable for new infrastructure and topology, but it is insufficient for our use case, which is to bring existing infrastructure under the management of Terraform, and allow it to be recreated as-is by Terraform.

> Declaring every single topology item using Terraform (or similar) resources is not necessary and likely means the operator does not fully understand how certain RabbitMQ features work, namely that federation sets up its own resources and may
use internal properties or markers that applications are not expected to use or care about.

This is quite presumptive and dismissive. We don't declare every topology item with Terraform, though we do wish to declare some, and we understand quite well how these features work. Our use case doesn't involve the federation plugin in any way and we're doing it as we are specifically because it's outside of our applications and they should not have to care about this particular detail.

---

It would be great to be able to replace internal exchanges with other mechanisms, but until there major server and client and protocol versions which don't expose the flag in any way, and older servers and clients are unsupported, and (ideally) there's a non-regex fine-grained permissions mechanism which can conveniently duplicate the publishing restrictions, then I think it's perfectly reasonable for a client to expose functionality already exposed and documented by the server. Regardless of original intent the reality is the feature is public and useful and used.
