### ISSUE TITLE
GetQueue on a nonexistent resource returns Unmarshal error

### ISSUE THREAD

**Issue by thavlik** [michaelklishin/rabbit-hole#132]
Hey! I appreciate this great open source software. It is helping me out a lot. I have a bug report for ya:

**Expected Behavior**
GetQueue() (and maybe others) should return nil or a unique error indicating there is no queue with the given name.

**Actual Behavior**
When `/queue/${queueName}` is invoked with a nonexistent queue, the following response is returned:

`{"error":"Object Not Found","reason":"Not Found"}`

Rabbit-hole makes no provisions to handle this, and upon unmarshaling, returns the following error:

`Failed to create consumer: json: cannot unmarshal array into Go struct field DetailedQueueInfo.owner_pid_details of type rabbithole.OwnerPidDetails`

I might submit a PR depending on how tedious it'll seem to fix this and/or if people ask for a PR.

Tom

**Comment by michaelklishin** [comment]
You are welcome to contribute a pull request that would return an error based on the response status. Thank you.

**Comment by mkuratczyk** [comment]
I can't reproduce this issue. `executeAndParseRequest()` returns an error and does not attempt to unmarshal the response: https://github.com/michaelklishin/rabbit-hole/blob/master/client.go#L138-L144. I'm happy to fix this problem if someone can show to to trigger it. Otherwise, I think it can be closed.

**Comment by michaelklishin** [comment]
We might have addressed this in 2.4.0 as part of something else.
