### ISSUE TITLE
Incorrect JSON tag for QueueInfo.Status on rabbitMQ 3.7.15

### ISSUE THREAD

**Issue by wangdrew** [michaelklishin/rabbit-hole#134]
RabbitMQ v3.7.15 `GET /api/queues/*` endpoint uses `state` rather than `status` for the JSON field name. My guess is the field name might have changed from previous versions of rabbitMQ? (if true, seems like the backwards compatibility philosophy there was 🤷‍♂) 

Proposal is to add an additional field to `QueueInfo` struct:
```
// Queue status for versions >= vX.X.X
State string `json:"state"`
```

**Update (June 26, 2019):**
Confirmed v3.4.2 (oldest image I could find on docker hub for `rabbitmq`) is also using `state`. Might be better just to change the underlying tag instead of adding an additional field:
```
Status string `json:"state"`
```

**Comment by michaelklishin** [comment]
Addressed in #135. Thank you!
