### ISSUE TITLE
Unable to require v2.0.0 due to outdated go.mod

### ISSUE THREAD

**Issue by cyrilgdn** [michaelklishin/rabbit-hole#146]
This module does not seem to not follow correctly the [Go semantic import versioning](https://github.com/golang/go/wiki/Modules#semantic-import-versioning) since you released the v2

Releasing a [v2 or higher](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher) apparently needs to add a /v2 at the end of the module path in `go.mod`(so ``module github.com/michaelklishin/rabbit-hole/v2``).

Because of that, we are not able to require the v2.0.0:
```bash
$ mkdir /tmp/test_mod && /tmp/test_mod
$ go mod init test
go: creating new go.mod: module test
$ go get github.com/michaelklishin/rabbit-hole@v2.0.0
go: finding github.com v2.0.0
go: finding github.com/michaelklishin/rabbit-hole v2.0.0
go: finding github.com/michaelklishin v2.0.0
go: finding github.com/michaelklishin/rabbit-hole v2.0.0
go get github.com/michaelklishin/rabbit-hole@v2.0.0: github.com/michaelklishin/rabbit-hole@v2.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```
As you can see, we got the following error:
> invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

**Comment by michaelklishin** [comment]
@cyrilgdn is https://github.com/michaelklishin/rabbit-hole/commit/8d2d6fab2ee6cea35ab05de97bede2cc6b2e27f0 sufficient?

**Comment by michaelklishin** [comment]
Specifically, do we need to bump the version and release `2.1.0` so that the `go.mod` changes are included into the tag?

**Comment by cyrilgdn** [comment]
> is [8d2d6fa](https://github.com/michaelklishin/rabbit-hole/commit/8d2d6fab2ee6cea35ab05de97bede2cc6b2e27f0) sufficient?

@michaelklishin I think so, I'm not an expert though, I discovered all this new major releases semantic versions stuff when I opened this issue :sweat_smile: 

> Specifically, do we need to bump the version and release 2.1.0 so that the go.mod changes are included into the tag?

Yes as the v2.0.0 is not in the right format
