### ISSUE TITLE
Shovel API: src-delete-after takes multiple types

### ISSUE THREAD

**Issue by justinbaur** [michaelklishin/rabbit-hole#149]
Just logging something I've ran up against and may be able to contribute to at some point.

Based on the latest [RabbitMQ documentation](https://www.rabbitmq.com/shovel-dynamic.html) the src-delete-after attribute requires the json type to be an integer if setting temporary shovel length to an integer length.

Only supported options for rabbit-hole are "never" and "queue-length" as the json payload only supports sending a string.
https://github.com/michaelklishin/rabbit-hole/blob/a4ba81f8edb65edcb7e50f8b766f597b4f2f6a8b/shovels.go#L35

**Comment by michaelklishin** [comment]
A PR that lifts this limitation would be welcome.
