### ISSUE TITLE
http client helper functions check for errors in the wrong order

### ISSUE THREAD

**Issue by mammothbane** [michaelklishin/rabbit-hole#158]
See e.g. https://github.com/michaelklishin/rabbit-hole/blob/master/client.go#L85-L89

If constructing the request fails, this code panics because the request is `nil`, rather than returning the error.

**Comment by michaelklishin** [comment]
Addressed in https://github.com/michaelklishin/rabbit-hole/commit/c751dcf5f341a820a10ad4fa5f7b3688e9db092d.
