### ISSUE TITLE
/api/exchanges/vhost/name/publish and /api/queues/vhost/name/get	 Not available	

### ISSUE THREAD

**Issue by xinln** [michaelklishin/rabbit-hole#161]
/api/exchanges/vhost/name/publish and /api/queues/vhost/name/get  Can't find the corresponding api.
Is it not implement？

**Comment by michaelklishin** [comment]
This issue is open which means it has never been implemented. Publishing over HTTP API is a last resort measure so I would close this without implementing.

**Comment by michaelklishin** [comment]
This won't be addressed unless there is a critical mass of demand for it. Publish and consume using actual messaging client libraries, not those endpoints.
