### ISSUE TITLE
SaltedPasswordHashSHA256 not match with rabbitmq computing password hash rule

### ISSUE THREAD

**Issue by ridwankustanto** [michaelklishin/rabbit-hole#165]
Hi,

I was facing a problem while trying to create a new user. I used code like the example:

    hash := SaltedPasswordHashSHA256("password-s3krE7")
          resp, err := rmqc.PutUser("my.user", UserSettings{
          PasswordHash: hash,
          HashingAlgorithm: HashingAlgorithmSHA256,
          Tags: "management,policymaker"})

But turned out it gave me 400 bad request. It looks like the function to generate password hash produced strange string `hash: �nh7��܄���P���#���d��m:�#R�` and it makes the request labelled as bad request. After searching around and read guide to computing password hash, I did a bit of change. And this worked for me:

    func generatePasswordHash(password string) string {
	    salt := generateSalt(4)
	    hash := generateHashSha256(salt, password)
	    hash = append(salt[:], []byte(hash[:])...)

	    return base64.StdEncoding.EncodeToString(hash[:])
     }

    func generateHashSha256(salt []byte, password string) []byte {
        temp_hash := sha256.Sum256(append(salt[:], []byte(password)...))
	    return temp_hash[:]
     }

I hope it would help someone in the future. Thanks for this package! 😁

**Comment by michaelklishin** [comment]
`SaltedPasswordHashSHA256 ` returns a pair of strings. The example should use `Base64EncodedSaltedPasswordHashSHA256` (which your example reimplements).

**Comment by michaelklishin** [comment]
Indeed, if `SaltedPasswordHashSHA256 ` is swapped for `SaltedPasswordHashSHA256 ` then we get [what this test case does](https://github.com/michaelklishin/rabbit-hole/blob/555e60e096f9bfe87adc3b8d1a748fdb71881dc2/rabbithole_test.go#L817).

Thank you, this was a documentation issue indeed.
