### ISSUE TITLE
Reading messages from a queue

### ISSUE THREAD

**Issue by dominikbraun** [michaelklishin/rabbit-hole#176]
Hi,

it seems to me that the `/api/queues/vhost/name/get` endpoint for retrieving messages in a queue has not been implemented yet. The `GetQueue` method only calls `/api/queues/vhost/name`. Does this have a specific reason?

Thanks in advance!

**Comment by michaelklishin** [comment]
Consuming messages over the HTTP API is **highly** discouraged. It means polling and [connection churn](https://www.rabbitmq.com/connections.html#high-connection-churn) (the API endpoint will have to use short lived connections). So there are no plans to implement that endpoint and I would never recommend it to anyone.
