### ISSUE TITLE
Do you plan to support 3.9 ?

### ISSUE THREAD

**Issue by NargiT** [michaelklishin/rabbit-hole#202]
Hello,

Now that [3.9 was released](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.9.0) do you plan to support it ?

I am asking this because we would like to use [teraform provider for rabbitmq](https://github.com/cyrilgdn/terraform-provider-rabbitmq) in order to automate our new shiny infrastructure. The project uses rabbit-hole to tackle the REST api.

Thanks

**Comment by michaelklishin** [comment]
There is nothing special about 3.9. If any endpoints are missing, you and other users are welcome to contribute it. This is open source software after all.
