### ISSUE TITLE
Add idle_since to `QueueInfo` struct

### ISSUE THREAD

**Issue by jherman** [michaelklishin/rabbit-hole#205]
Hi,

Not sure if this was intentionally left out, but when a queue has been idle the returned JSON from the API will have the property idle_since with the time associated to it.  This is usefully when queues have a TTL attached.

It would be great if this was included with `QueueInfo`.

Thanks.

**Comment by michaelklishin** [comment]
This is a field that Team RabbitMQ considers to be an implementation detail, so we are not interested in heavily exposing it.
