### ISSUE TITLE
ListConsumers function returns unmarshal string error when run against a 3.9 instance. 

### ISSUE THREAD

**Issue by HariNarayananMohan** [michaelklishin/rabbit-hole#228]
When I try to invoke a listConsumer or listconsumerIn function on the httpclient against a RabbitMQ 3.9 Instance, the below error is received. 

`json: cannot unmarshal string into Go struct field BriefChannelDetail.channel_details.peer_port of type int`

The same function works perfectly fine and returns the consumer list when run against a RabbitMQ 3.8 Instance. 

Also, when I tried to get the json output directly by hitting the GET request to rabbitmq api, I don't see any difference between 3.8 and 3.9 output. 

Both peer_port field doesn't seem to contain string. They looks like integer to me. 

Output from 3.8 instance 
```
{"arguments":{},
"ack_required":true,
"active":true,
"activity_status":"single_active",
"channel_details":{
	"connection_name":"localhost:52542 -> localhost:5671",
	"name":"localhost:52542 -> localhost:5671 (1)",
	"node":"rabbit@...",
	"number":1,
	"peer_host":"localhost",
	"peer_port":52542,
	"user":"admin"},
	"consumer_tag":"amq.ctag-4f3CAuaqSNDnET45D1DOnw",
	"exclusive":false,
	"prefetch_count":1000,
	"queue":{"name":"...",
	"vhost":"/"}
},
```
Output from 3.9 Instance 
```
{"arguments":{},
"ack_required":true,
"active":true,
"activity_status":"single_active",
"channel_details":{
	"connection_name":"localhost:36380 -> localhost:5671",
	"name":"localhost:36380 -> localhost:5671 (130)",
	"node":"rabbit@....",
	"number":130,
	"peer_host":"localhost",
	"peer_port":36380,
	"user":"admin"},
	"consumer_tag":"fbdb6dad-2248-42cd-6d7b-d14a8b865ec5",
	"exclusive":false,
	"prefetch_count":1,
	"queue":{"name":"...",
	"vhost":"/"}
},
```

**Comment by HariNarayananMohan** [comment]
@michaelklishin any thoughts please ?

**Comment by michaelklishin** [comment]
How can I reproduce? How does 3.10 behave? I wouldn't worry about 3.8 as it is days from going completely EOL.

**Comment by michaelklishin** [comment]
The responses seem identical, at least without the nested `queue` object that has been excluded.

Something must be different about those consumers. Without a way to reproduce, I wouldn't guess what it may be.

Please compare 3.9 to 3.10, we won't address anything 3.8-specific.

**Comment by HariNarayananMohan** [comment]
@michaelklishin thanks for looking into this. Unfortunately I do not have access to a 3.10 rabbitmq instance. is there any other way this could be sorted ?

**Comment by michaelklishin** [comment]
``` shell
docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.10-management
```

would get you a 3.10 instance. We need a way to reproduce or we won't be able to help.

**Comment by HariNarayananMohan** [comment]
> ```shell
> docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.10-management
> ```
> 
> would get you a 3.10 instance. We need a way to reproduce or we won't be able to help.

thank you! let me try that.

**Comment by HariNarayananMohan** [comment]
@michaelklishin Thanks for waiting. I did run try the similar test against 3.10 and I did not receive any error like what is returned for 3.9. And when I tried to get the json response directly this is what it looks like for 3.10
```[{"arguments":{},
"ack_required":true,
"active":true,
"activity_status":"up",
"channel_details":{
	"connection_name":"....:64196 -> ...:5672",
	"name":"...:64196 -> ...:5672 (1)",
	"node":"rabbit@...",
	"number":1,
	"peer_host":"...",
	"peer_port":64196,
	"user":"guest"},
	"consumer_tag":"ctag-/var/folders/64/lwbnnbx51hzc323m9k6kvs5m0000gn/T/go-build2853156719/b001/exe/pubsub-1",
	"exclusive":true,
	"prefetch_count":0,
	"queue":{"name":"...",
	"vhost":"/"}
}]
```
So this listconsumer function seems to be the issue only when run against a 3.9 RabbitMQ instance. 
I also noticed the the ListChannels function is returning a `strconv.ParseInt: parsing "undefined": invalid syntax` error. 
Again, the ListChannels function resturns proper response when run against a 3.10 instance.

**Comment by michaelklishin** [comment]
Without a way to reproduce and given that most development efforts now go into 3.10.x, which is not exactly brand new any more, I'm afraid I have to close this as a `wontfix`.
