### ISSUE TITLE
Support setting a default queue type on vhosts

### ISSUE THREAD

**Issue by mqhenning** [michaelklishin/rabbit-hole#258]
Greetings! 
 
Since RabbitMQ now supports a `default-queue-type` parameter for vhosts, I suggest supporting this parameter here. The resulting behavior is that queues created in a vhost that don't set a queue type are created with the specified default. Accepted values are `quorum`, `classic`, and `stream`. I'll take a shot at a pull request, if I have time to do so and no one beats me to it.

Useful context: https://www.rabbitmq.com/rabbitmqctl.8.html#Virtual_hosts

**Comment by michaelklishin** [comment]
@mqhenning you are welcome to submit a PR.
