### ISSUE TITLE
Error when trying to declare a queue

### ISSUE THREAD

**Issue by liquidmetal** [michaelklishin/rabbit-hole#74]
```go
mq, err := rabbithole.NewClient("http://localhost:5672/", "", "")
_, err := mq.DeclareQueue("/", "some.queue", rabbithole.QueueSettings{Durable: true})
```

The error I see on when I run this code is:

```
Put http://localhost:5672/api/queues/%2F/some.queue: malformed HTTP response "AMQP\x00\x00\t\x01"
```

I'm using `go version go1.6 linux/amd64` and rabbitmq 3.6.1. Any help on what might be happening?

**Comment by michaelklishin** [comment]
Port 5672 is used by AMQP 0-9-1 and 1.0, not HTTP API. Please consult [management plugin docs](http://rabbitmq.com/management.html).

Note that rabbit-hole's own docs use a different port:

``` go
// URI, username, password
rmqc, _ = NewClient("http://127.0.0.1:15672", "guest", "guest")
```

**Comment by liquidmetal** [comment]
Thanks! Maybe add an error message saying you've incorrectly connected to the AMQP port? I suspect lots of people would have this issue.

**Comment by michaelklishin** [comment]
@liquidmetal RabbitMQ can be configured to use any port for any protocol. This is not a common issue I personally see reported for this client or rabbitmq-users in general.
