### ISSUE TITLE
ConsumerUtilisation: cannot unmarshal string into Go value of type float64

### ISSUE THREAD

**Issue by loafoe** [michaelklishin/rabbit-hole#81]
Running into this issue on servers with RabbitMQ < `3.5.7`
Related to https://github.com/rabbitmq/rabbitmq-management/issues/26

```javascript
[
  {
   ...
   "idle_since": "2016-07-07 7:26:36",
   "consumer_utilisation": "",
   "policy": "",
   ...
  }
]
```

https://github.com/michaelklishin/rabbit-hole/blob/master/queues.go#L67

```golang
   	// Utilisation of all the consumers
	ConsumerUtilisation float64 `json:"consumer_utilisation"`
```

Results in a marshalling error: **json: cannot unmarshal string into Go value of type float64**

**Comment by michaelklishin** [comment]
See https://github.com/rabbitmq/rabbitmq-management/issues/100.
