### ISSUE TITLE
[rfc] support message_stats -> * -> samples

### ISSUE THREAD

**Issue by jippi** [michaelklishin/rabbit-hole#88]
Hi,

First, thank you for a very usable piece of open source software! :) 

If you request the RabbitMQ management API with additional GET arguments, you can also get sample data from queue(s), which is used to graph activity charts in the UI.

Today these options are not exposed in this library, is that should that is planned? 

**Example query**

`/api/queues/%2F?lengths_age=1800&lengths_incr=30&msg_rates_age=1800&msg_rates_incr=30&data_rates_age=1800&data_rates_incr=30&columns=name,messages_ready,consumer_utilisation,message_stats.publish_details,message_stats.ack_details,consumer_utilisation`

**Comment by michaelklishin** [comment]
No. Not only this is the first time it is requested, I'm not even sure this feature is still around after https://github.com/rabbitmq/rabbitmq-management/issues/236.

Why would you need samples beyond debugging the plugin itself?

**Comment by michaelklishin** [comment]
OK, I'm being told that the feature is still there. I guess we can add support for query options and parse back extra results. Let's discuss this in #89.
