### ISSUE TITLE
Support specifying query parameters

### ISSUE THREAD

**Issue by jippi** [michaelklishin/rabbit-hole#89]
Most management endpoints support limiting the number of fields you get back in the API response, using `?fields=` 

Is this something that is planned to be added? :)

**Comment by michaelklishin** [comment]
How would we do it, introduce a breaking change for every single function or introduce another version of every function, e.g. `GetConnectionWithFields`? The latter sounds OK but it's a non-trivial amount of effort if you consider tests.

Honestly, I see little value in it. This is just not something I've seen requested for this or any other HTTP API client before.

Given the above, I don't think it's worth the effort.

**Comment by michaelklishin** [comment]
Or, if you also consider #88, `GetConnectionsWithQueryParameters`? That sounds like a more generic solution that's more justifiable. Still, not a priority for me personally but I'd consider it if someone decides to contribute it :)

**Comment by jippi** [comment]
@michaelklishin my Go is still newbie'ish, how would you go about implementing it ? I can give it a shot, as i need it for github.com/jippi/nomad-auto-scale :) 

Any tips on what add where would be highly appreciated

**Comment by michaelklishin** [comment]
We already have

``` go
func (c *Client) ListConnections() (rec []ConnectionInfo, err error)
```

and need to add

``` go
func (c *Client) ListConnectionsWithQuery(url.Values qs) (rec []ConnectionInfo, err error)
```

because function overloading is not an option in Go. [url.Values](https://golang.org/pkg/net/url/#Values) seems to be the primary way of setting [query strings in Go's HTTP client](http://stackoverflow.com/questions/30652577/go-doing-a-get-request-and-building-the-querystring).

For each such function we need at least one new test. See [Running Tests](https://github.com/michaelklishin/rabbit-hole/blob/master/CONTRIBUTING.md).

**Comment by jippi** [comment]
@michaelklishin would it be okay to implement for just the methods i need ? I'm far from expert in the APIs, so don't know which takes and does not take query arguments

**Comment by michaelklishin** [comment]
@jippi sure. I'm more worried that we wouldn't be able to update JSON parser mappings in sensible way than only having a few `*WithQuery` functions. I suspect that only `List*` and some `Get*` functions (well, their respective endpoints) can potentially support query strings.

**Comment by jippi** [comment]
@michaelklishin if the struct contains all the options (i think it's just samples missing ?) couldn't they just be optional in the json parsing and remain an empty struct if not returned by the API?

**Comment by michaelklishin** [comment]
@jippi the fields are optional in nature. They need sensible names and adequately named records.

**Comment by jippi** [comment]
@michaelklishin can you please give #90 a review if I'm way off track or if the changes do make sense to you :)

**Comment by jippi** [comment]
Closing issue as a PR is open :)

**Comment by michaelklishin** [comment]
It's fine to keep it open until #90 is merged.

**Comment by michaelklishin** [comment]
@jippi thank you!
