### ISSUE TITLE
Invalid URI encoding with `url.QueryEscape()`

### ISSUE THREAD

**Issue by dumbbell** [michaelklishin/rabbit-hole#95]
The client uses `url.QueryEscape()` to escape path segments in the created URLs. Unfortunately, this module produces invalid path segments: it transforms spaces to `+`. This is fine for query string, but not path segments.

Newer versions of Cowboy, which have a stricter URL parsing, leave the `+` characters alone. So when a user of this HTTP client wants to create eg. a vhost with a space in it, he ends up with a vhost with a `+`.

**Comment by michaelklishin** [comment]
Fortunately [Go URL in recent version provides built-in %-encoding support](https://github.com/golang/go/commit/874a605af0764a8f340c3de65406963f514e21bc).

**Comment by michaelklishin** [comment]
[Spoke too soon](https://github.com/golang/go/issues/13737), a suitable built-in method seems to have been added in https://github.com/golang/go/commit/7e2bf952a905f16a17099970392ea17545cdd193 which is scheduled for Go 1.8.

**Comment by dumbbell** [comment]
Thank you for the quick fix! I confirm the testsuite is now green when Cowboy 1.1.0 is used.
