### ISSUE TITLE
PutFederationUpstream with default AckMode

### ISSUE THREAD

**Issue by e-nikolov** [michaelklishin/rabbit-hole#99]
Seems that if the AckMode is left with default value when using PutFederationUpstream, the API returns "Status: 400 Bad Request". 

Adding "omitempty" to the AckMode's json tag in FederationDefinition appears to fix the issue.

**Comment by michaelklishin** [comment]
@e-nikolov please submit a pull request.

**Comment by e-nikolov** [comment]
@michaelklishin There should also be support for specifying an Exchange or a Queue in the FederationDefinition. Should I make a separate pull request for those, or add them together?
